title: Aleksandr Shurygin — Full Stack Web Developer
description: Resume and professional profile of Aleksandr Shurygin
url: "https://landrail8.github.io"
baseurl: ""
default_locale: ru
locales:
  - ru
  - en
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false

exclude:
  - scripts
  - README.md
  - .translation-memory
  - ru/_config.yml
  - ru/_data
  - ru/_includes
  - ru/_layouts
  - ru/_sass
  - ru/assets
